baseurl = "/"
languageCode = "en-us"
title = "Yumou Qiu's website"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 2
[[menu.main]]
    name = "Publication"
    url = "/publication/"
    weight = 3
[[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 4
[[menu.main]]
    name = "Presentation"
    url = "/presentation/"
    weight = 5

[params]
    description = "Yumou Qiu's website."
    footer = "&copy; [Yumou Qiu](https://yumou.org) 2019 | [Github](https://github.com/yumouqiu)"
    